
PRAGMA foreign_keys=OFF;

DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS MARCA;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS COMPRA;
DROP TABLE IF EXISTS ESTOQUE;
DROP TABLE IF EXISTS SAIDA;

PRAGMA foreign_keys=ON;

CREATE TABLE MARCA(
    ID INTEGER CONSTRAINT PK_MARCA PRIMARY KEY AUTOINCREMENT NOT NULL,
    NOME VARCHAR(521) UNIQUE,
    EMPRESA VARCHAR(521) NOT NULL
);
CREATE TABLE DEPARTAMENTO(
    ID INTEGER CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY AUTOINCREMENT NOT NULL,
    NOME VARCHAR(521) UNIQUE
);
CREATE TABLE PRODUTO(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NOME VARCHAR(521) NOT NULL,
    ID_MARCA INTEGER NOT NULL,
    ID_DEPT INTEGER NOT NULL, 
    CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY(ID_DEPT) REFERENCES DEPARTAMENTO(ID),
    CONSTRAINT FK_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID)
);
CREATE TABLE COMPRA(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    PRECO DOUBLE NOT NULL,
    DT DATE NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    TOTAL INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID)
);
CREATE TABLE SAIDA(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    DT DATE NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    ID_COMPRA INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    FOREIGN KEY(ID_COMPRA) REFERENCES COMPRA(ID),
    FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID)
);


INSERT INTO MARCA (NOME, EMPRESA) VALUES ('Ruffles','Pepsico');
INSERT INTO MARCA (NOME, EMPRESA) VALUES ('Qualy','Sadia');
INSERT INTO MARCA (NOME, EMPRESA) VALUES ('Gilette','Procter & Gamble');

INSERT INTO DEPARTAMENTO (NOME) VALUES ('Alimentos');
INSERT INTO DEPARTAMENTO (NOME) VALUES ('Higiene');

INSERT INTO PRODUTO (NOME, ID_MARCA, ID_DEPT) VALUES ('Batata',1,1);

SELECT * FROM MARCA;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM PRODUTO;
DELETE FROM DEPARTAMENTO WHERE ID=1;
DELETE FROM MARCA WHERE ID=1;
DELETE FROM DEPARTAMENTO WHERE ID=2;
DELETE FROM MARCA WHERE ID=2;
DELETE FROM PRODUTO WHERE ID=1;